"""
Synthetic Test-Data Generator — v8.0
====================================
Generates structurally faithful test data (fewer rows, SAME schema) so the
pipeline can be smoke-tested end-to-end without the real files:

  * recs2020_public_v7.csv  — if the RECS 2020 codebook xlsx is present in
    data/, ALL 799 codebook columns are emitted (exact structure); otherwise
    a rich key-column subset is used (the pipeline only reads named columns).
    Energy columns are generated by a physics-inspired generative model
    calibrated to published RECS 2020 statistics (EUI ~42 kBtu/sqft,
    heating share ~40%).
  * tmy3.csv                — hourly (69 TMY3-format columns) for N stations.
  * TMY3_StationsMeta.csv   — station metadata (State / Lat / Lon / Elev / Class).
  * upgrade{0,3,4,10,11,15}.csv.gz — ResStock 2025.1 naming ("in.*", "out.*..unit").
    All upgrade files share the SAME leading buildings (like real ResStock),
    so upgrade-vs-baseline delta measurement is meaningful.
  * spatial_tract_lookup_table.csv — 27-column placeholder (not used by v8).

Usage:
    python tools/make_test_data.py --recs-rows 4000 --resstock-rows 8000 --tmy3-stations 12
"""

import argparse
import gzip
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
CODEBOOK = DATA / "RECS 2020 Codebook for Public File - v7.xlsx"

RNG = np.random.default_rng(42)

# ---------------------------------------------------------------------------
# States (postal, name, region, division, HDD65, CDD65, weight)
# ---------------------------------------------------------------------------
STATES = [
    ("CA", "California", "W", "Pacific", 2600, 900, 3.0),
    ("TX", "Texas", "S", "West South Central", 1500, 3000, 2.6),
    ("FL", "Florida", "S", "South Atlantic", 500, 3800, 2.2),
    ("NY", "New York", "NE", "Middle Atlantic", 6000, 600, 2.0),
    ("IL", "Illinois", "MW", "East North Central", 6200, 900, 1.4),
    ("PA", "Pennsylvania", "NE", "Middle Atlantic", 5600, 650, 1.4),
    ("OH", "Ohio", "MW", "East North Central", 5800, 800, 1.3),
    ("GA", "Georgia", "S", "South Atlantic", 2800, 2000, 1.2),
    ("NC", "North Carolina", "S", "South Atlantic", 3300, 1700, 1.2),
    ("MI", "Michigan", "MW", "East North Central", 6500, 600, 1.2),
    ("WA", "Washington", "W", "Pacific", 4800, 300, 0.9),
    ("AZ", "Arizona", "W", "Mountain", 1600, 3400, 0.9),
    ("MN", "Minnesota", "MW", "West North Central", 8000, 450, 0.8),
    ("CO", "Colorado", "W", "Mountain", 6100, 700, 0.8),
    ("VA", "Virginia", "S", "South Atlantic", 3900, 1400, 0.9),
    ("MA", "Massachusetts", "NE", "New England", 5900, 550, 0.8),
    ("WI", "Wisconsin", "MW", "East North Central", 7400, 400, 0.7),
    ("MO", "Missouri", "MW", "West North Central", 4900, 1300, 0.7),
    ("TN", "Tennessee", "S", "East South Central", 3600, 1600, 0.7),
    ("IN", "Indiana", "MW", "East North Central", 5700, 900, 0.7),
    ("NJ", "New Jersey", "NE", "Middle Atlantic", 5100, 900, 0.9),
    ("MD", "Maryland", "S", "South Atlantic", 4600, 1200, 0.7),
    ("OR", "Oregon", "W", "Pacific", 4600, 250, 0.6),
    ("LA", "Louisiana", "S", "West South Central", 1900, 2800, 0.6),
    ("AL", "Alabama", "S", "East South Central", 2700, 2100, 0.6),
    ("SC", "South Carolina", "S", "South Atlantic", 2500, 2200, 0.6),
    ("KY", "Kentucky", "S", "East South Central", 4200, 1300, 0.5),
    ("OK", "Oklahoma", "S", "West South Central", 3600, 2100, 0.5),
    ("CT", "Connecticut", "NE", "New England", 6000, 500, 0.5),
    ("IA", "Iowa", "MW", "West North Central", 6800, 700, 0.5),
    ("UT", "Utah", "W", "Mountain", 5600, 900, 0.5),
    ("NV", "Nevada", "W", "Mountain", 4200, 1700, 0.5),
    ("AR", "Arkansas", "S", "West South Central", 3700, 1900, 0.4),
    ("KS", "Kansas", "MW", "West North Central", 5200, 1400, 0.4),
    ("NE", "Nebraska", "MW", "West North Central", 6300, 1000, 0.4),
    ("NM", "New Mexico", "W", "Mountain", 4300, 1200, 0.4),
    ("ID", "Idaho", "W", "Mountain", 5900, 500, 0.3),
    ("ME", "Maine", "NE", "New England", 7200, 300, 0.3),
    ("NH", "New Hampshire", "NE", "New England", 7000, 350, 0.3),
    ("RI", "Rhode Island", "NE", "New England", 5800, 500, 0.2),
    ("MT", "Montana", "W", "Mountain", 7400, 350, 0.2),
    ("ND", "North Dakota", "MW", "West North Central", 8600, 500, 0.2),
    ("SD", "South Dakota", "MW", "West North Central", 7600, 600, 0.2),
    ("VT", "Vermont", "NE", "New England", 7600, 300, 0.2),
    ("WY", "Wyoming", "W", "Mountain", 7100, 400, 0.2),
    ("DE", "Delaware", "S", "South Atlantic", 4800, 1100, 0.2),
    ("AK", "Alaska", "W", "Pacific", 10500, 50, 0.15),
    ("HI", "Hawaii", "W", "Pacific", 0, 4200, 0.3),
    ("WV", "West Virginia", "S", "South Atlantic", 4900, 1000, 0.3),
    ("MS", "Mississippi", "S", "East South Central", 2400, 2400, 0.4),
    ("DC", "District of Columbia", "S", "South Atlantic", 4300, 1300, 0.15),
]
STATE_DF = pd.DataFrame(STATES, columns=["postal", "name", "region", "division",
                                         "hdd", "cdd", "w"])

# TMY3 hourly format (NREL/TP-581-43156, 69 columns)
TMY3_COLUMNS = [
    "Station number", "Date (MM/DD/YYYY)", "Time (HH:MM)", "ETR (W/m^2)",
    "ETRN (W/m^2)", "GHI (W/m^2)", "GHI source", "GHI uncert", "DNI (W/m^2)",
    "DNI source", "DNI uncert", "DHI (W/m^2)", "DHI source", "DHI uncert",
    "GH illum (lx)", "GH illum source", "Direct normal illum (lx)",
    "Direct normal illum source", "Diffuse horizontal illum (lx)",
    "Diffuse horizontal illum source", "Zenith lum (Cd/m^2)",
    "Zenith lum source", "TotCld (tenths)", "TotCld source", "TotCld uncert",
    "OpqCld (tenths)", "OpqCld source", "OpqCld uncert", "Dry-bulb (C)",
    "Dry-bulb source", "Dry-bulb uncert", "Dew-point (C)", "Dew-point source",
    "Dew-point uncert", "RHum (%)", "RHum source", "RHum uncert",
    "Pressure (mbar)", "Pressure source", "Pressure uncert", "Wdir (degrees)",
    "Wdir source", "Wdir uncert", "Wspd (m/s)", "Wspd source", "Wspd uncert",
    "Hvis (m)", "Hvis source", "Hvis uncert", "CeilHgt (m)", "CeilHgt source",
    "CeilHgt uncert", "Pwat (cm)", "Pwat source", "Pwat uncert",
    "AOD (unitless)", "AOD source", "AOD uncert", "Alb (unitless)",
    "Alb source", "Alb uncert", "Lprecip quantity (hr)", "Lprecip depth (mm)",
    "Lprecip source", "Lprecip uncert", "PresWth (METAR code)",
    "PresWth source", "PresWth uncert",
]


def _ln(mean=1.0, sigma=0.4, n=1):
    return RNG.lognormal(np.log(mean) - sigma ** 2 / 2, sigma, n)


# ===========================================================================
# RECS 2020
# ===========================================================================
def make_recs(n_rows: int) -> pd.DataFrame:
    n = n_rows
    st_idx = RNG.choice(len(STATE_DF), n, p=STATE_DF["w"] / STATE_DF["w"].sum())
    st = STATE_DF.iloc[st_idx].reset_index(drop=True)

    hdd = np.clip(st["hdd"].values * _ln(1, 0.12, n), 0, None)
    cdd = np.clip(st["cdd"].values * _ln(1, 0.12, n), 0, None)

    def ba_zone(h, c):
        if h >= 7000: return "Very-Cold"
        if h >= 5000: return "Cold"
        if h >= 3800 and c < 2000: return "Marine" if RNG.random() < 0.3 else "Mixed-Humid"
        if c >= 2500: return "Hot-Humid" if RNG.random() < 0.7 else "Hot-Dry"
        return "Mixed-Humid" if RNG.random() < 0.6 else "Mixed-Dry"

    ba = [ba_zone(h, c) for h, c in zip(hdd, cdd)]

    typehuq = RNG.choice([1, 2, 3, 4, 5], n, p=[0.06, 0.63, 0.06, 0.10, 0.15])
    sqft = np.clip(_ln(1, 0.35, n) * np.where(typehuq == 2, 2300,
                    np.where(typehuq == 1, 1100, 1400)), 200, 15000).round(0)
    stories = np.where(typehuq == 1, 1,
                       np.where(typehuq >= 4, RNG.choice([1, 2, 3], n, p=[0.4, 0.4, 0.2]),
                                RNG.choice([1, 2, 3], n, p=[0.45, 0.45, 0.1]))).astype(float)
    bedrooms = np.clip((sqft / 600 + RNG.normal(0, 0.6, n)).round(0), 0, 6)
    occ = np.clip(RNG.poisson(2.2, n) + 1, 1, 10).astype(float)
    yearrange = RNG.choice(np.arange(1, 12), n,
                           p=[0.09, 0.07, 0.09, 0.11, 0.13, 0.13, 0.12, 0.11, 0.07, 0.05, 0.03])
    walltype = RNG.choice([1, 2, 3, 4, 5, 6, 7], n,
                          p=[0.08, 0.50, 0.10, 0.12, 0.08, 0.05, 0.07])
    rooftype = RNG.choice([1, 2, 3, 4, 5, 6], n, p=[0.55, 0.15, 0.10, 0.05, 0.10, 0.05])
    adqinsul = np.where(yearrange <= 3,
                        RNG.choice([1, 2, 3, 4], n, p=[0.30, 0.35, 0.25, 0.10]),
                        RNG.choice([1, 2, 3, 4], n, p=[0.15, 0.30, 0.35, 0.20]))
    typeglass = np.where(yearrange <= 4, RNG.choice([1, 2, 3], n, p=[0.5, 0.45, 0.05]),
                         RNG.choice([1, 2, 3], n, p=[0.15, 0.75, 0.10]))
    windows = np.clip((sqft / 400 + RNG.normal(0, 1.5, n)).round(0), 1, 12).astype(float)
    drafty = np.where(yearrange <= 4,
                      RNG.choice([1, 2, 3, 4], n, p=[0.25, 0.35, 0.25, 0.15]),
                      RNG.choice([1, 2, 3, 4], n, p=[0.10, 0.25, 0.40, 0.25]))
    highceil = (RNG.random(n) < 0.25).astype(float)

    south = np.isin(st["region"].values, ["S"])
    cold = hdd > 5500
    fuelheat = np.where(
        south & (RNG.random(n) < 0.55), 5,
        np.where(cold & (RNG.random(n) < 0.65), 1,
                 RNG.choice([1, 2, 3, 5, 7], n, p=[0.45, 0.07, 0.08, 0.35, 0.05]))).astype(float)
    equipm = np.where(fuelheat == 5,
                      np.where(cold & (RNG.random(n) < 0.35), 10, RNG.choice([3, 10, 12], n, p=[0.3, 0.3, 0.4])),
                      RNG.choice([3, 4, 5, 7], n, p=[0.65, 0.05, 0.2, 0.1])).astype(float)
    aircond = (RNG.random(n) < np.where(south, 0.92, 0.72)).astype(float)
    typeac = np.where(aircond == 1, RNG.choice([1, 2], n, p=[0.7, 0.3]), 0).astype(float)

    # ---------------- physics-consistent energy model (kBtu) ----------------
    ceil_h = 9.0
    height = stories * ceil_h
    footprint = sqft / stories
    perimeter = 4 * np.sqrt(np.clip(footprint, 25, None))
    wall_area = perimeter * height
    u_wall = pd.Series(walltype).map({1: .30, 2: .18, 3: .25, 4: .20, 5: .22, 6: .35, 7: .28}).fillna(.22).values
    insul_f = pd.Series(adqinsul).map({1: 1.25, 2: 1.0, 3: 0.8, 4: 0.65}).fillna(1.0).values
    u_glass = pd.Series(typeglass).map({1: 1.0, 2: 0.55, 3: 0.35}).fillna(.65).values
    win_area = wall_area * np.clip(0.06 + 0.02 * windows, 0.08, 0.30)
    ach50 = pd.Series(drafty).map({1: 14., 2: 10., 3: 6.5, 4: 4.}).fillna(9.).values
    ua = (u_wall * insul_f * np.clip(wall_area - win_area, 0, None)
          + u_glass * win_area + 0.08 * insul_f * footprint + 0.10 * footprint
          + 0.018 * sqft * ceil_h * ach50 / 20)
    is_hp = (fuelheat == 5) & (equipm == 10)
    equip_factor = pd.Series(equipm).map({3: 1.00, 4: 0.85, 5: 0.92, 7: 0.88,
                                          10: 1.00, 12: 1.00}).fillna(0.95).values
    heat_eff = np.where(is_hp, 2.3, np.where(fuelheat == 5, 0.98,
                        pd.Series(fuelheat).map({1: .80, 2: .78, 3: .78, 7: .55}).fillna(.80).values
                        * equip_factor))
    beh = _ln(1.0, 0.25, n)  # behavioral/occupant variance — the irreducible part

    heat_load = ua * hdd * 24 / 1000 * beh
    totalbtusph = np.clip(heat_load / heat_eff * 0.30, 0, None)           # calib
    cool_load = (ua * 0.8 + 0.5 * 0.018 * sqft * ceil_h * ach50 / 20) * cdd * 24 / 1000
    cool_eff = np.where(typeac == 1, 3.2, np.where(typeac == 2, 2.6, 3.0))
    btuelcol = np.clip(cool_load / (cool_eff / 3.412) * aircond * beh * 0.20, 0, None)
    totalbtuwth = np.clip(occ * 25 * 8.34 * 70 * 365 / 1000 * beh *
                          np.where(fuelheat == 5, 1 / .92, 1 / .62) * 0.62, 0, None)
    btuellgt = np.clip((sqft / 90 * 125 + 500) * (1 - 0.5 * RNG.uniform(0, 1, n)) * beh * 1.05, 0, None)
    btuelrfg = np.clip(3200 * _ln(1, 0.25, n), 0, None)
    btuelapl = np.clip((occ * 1400 + sqft * 4.5 + 4000) * _ln(1, 0.30, n), 0, None)
    btuelplt = 0.30 * btuelapl
    btuelcok = np.where(RNG.random(n) < 0.6, 800 * _ln(1, 0.2, n), 0)

    elec_heat = np.where(fuelheat == 5, totalbtusph, 0)
    gas_heat = np.where(fuelheat == 1, totalbtusph, 0)
    fo_heat = np.where(fuelheat == 2, totalbtusph, 0)
    lp_heat = np.where(fuelheat == 3, totalbtusph, 0)
    elec_dhw = np.where(fuelheat == 5, totalbtuwth, 0)
    gas_dhw = np.where(fuelheat == 1, totalbtuwth, 0)

    btuel = elec_heat + btuelcol + elec_dhw + btuellgt + btuelrfg + btuelapl + btuelplt + btuelcok
    btung = gas_heat + gas_dhw
    btufo = fo_heat
    btulp = lp_heat
    totalbtu = btuel + btung + btufo + btulp
    kwh = btuel / 3.412

    df = pd.DataFrame({
        "DOEID": np.arange(1, n + 1),
        "REGIONC": st["region"].map({"W": "W", "S": "S", "MW": "MW", "NE": "NE"}).values,
        "DIVISION": st["division"].values,
        "STATE_FIPS": [f"{i % 56 + 1:02d}" for i in st_idx],
        "state_postal": st["postal"].values,
        "state_name": st["name"].values,
        "BA_climate": ba,
        "IECC_climate_code": [b.split("-")[0] for b in ba],
        "HDD65": hdd.round(0), "CDD65": cdd.round(0),
        "HDD30YR_PUB": (hdd * _ln(1, .05, n)).round(0),
        "CDD30YR_PUB": (cdd * _ln(1, .05, n)).round(0),
        "TYPEHUQ": typehuq, "TOTSQFT_EN": sqft, "STORIES": stories,
        "BEDROOMS": bedrooms.astype(float),
        "TOTROOMS": np.clip(bedrooms + RNG.poisson(3, n), 1, 15).astype(float),
        "NCOMBATH": np.clip(bedrooms / 2, 1, 4).round(0),
        "NHAFBATH": (RNG.random(n) < .4).astype(float),
        "NHSLDMEM": occ, "YEARMADERANGE": yearrange.astype(float),
        "KOWNRENT": RNG.choice([1, 2], n, p=[.66, .34]).astype(float),
        "WALLTYPE": walltype.astype(float), "ROOFTYPE": rooftype.astype(float),
        "ADQINSUL": adqinsul.astype(float), "TYPEGLASS": typeglass.astype(float),
        "WINDOWS": windows, "DRAFTY": drafty.astype(float),
        "HIGHCEIL": highceil, "FUELHEAT": fuelheat, "EQUIPM": equipm,
        "AIRCOND": aircond, "TYPEAC": typeac,
        "NUMFRIG": np.clip(RNG.poisson(1.1, n), 0, 4).astype(float),
        "TVCOLOR": np.clip(RNG.poisson(1.8, n), 0, 8).astype(float),
        "NUMPC": np.clip(RNG.poisson(1.2, n), 0, 6).astype(float),
        "DWASHER": (RNG.random(n) < .65).astype(float),
        "CWASHER": (RNG.random(n) < .8).astype(float),
        "DRYER": (RNG.random(n) < .75).astype(float),
        "SWIMPOOL": (RNG.random(n) < .06).astype(float),
        "RECFRIG": (RNG.random(n) < .25).astype(float),
        "HUMIDIF": (RNG.random(n) < .2).astype(float),
        "SMARTMETER": (RNG.random(n) < .45).astype(float),
        "INTELLIGHT": (RNG.random(n) < .15).astype(float),
        "SOLAR": (RNG.random(n) < .06).astype(float),
        "EV": (RNG.random(n) < .08).astype(float),
        "NWEIGHT": RNG.uniform(437, 29279, n).round(0),
        "TOTALBTU": totalbtu.round(0), "TOTALBTUSPH": totalbtusph.round(0),
        "TOTALBTUWTH": totalbtuwth.round(0),
        "BTUELCOL": btuelcol.round(0), "BTUELLGT": btuellgt.round(0),
        "BTUELSPH": elec_heat.round(0), "BTUELWTH": elec_dhw.round(0),
        "BTUELRFG": btuelrfg.round(0), "BTUELAPL": btuelapl.round(0),
        "BTUEL": btuel.round(0), "KWH": kwh.round(0),
        "BTUNG": btung.round(0), "THERMS": (btung / 100).round(0),
        "BTUFO": btufo.round(0), "BTULP": btulp.round(0),
        "TOTALDOL": (btuel * 0.037 + btung * 0.011).round(0),
    })

    # ---- structural filler ------------------------------------------------
    # imputation flags + replicate weights + a few generic survey columns
    for i in range(1, 61):
        df[f"NWEIGHT{i}"] = (df["NWEIGHT"] * _ln(1, .15, n)).round(0)
    for z in ["ZTOTSQFT", "ZNHSLDMEM", "ZFUELHEAT", "ZEQUIPM", "ZAIRCOND",
              "ZTYPEGLASS", "ZADQINSUL", "ZWALLTYPE", "ZDRAFTY", "ZWINDOWS"]:
        df[z] = (RNG.random(n) < 0.08).astype(float)
    for i in range(30):
        df[f"APPLFLAG{i:02d}"] = (RNG.random(n) < RNG.uniform(0.05, 0.6)).astype(float)

    # ---- exact codebook structure when available --------------------------
    if CODEBOOK.exists():
        try:
            cb = pd.read_excel(CODEBOOK, sheet_name=0)
            name_col = [c for c in cb.columns if "variable" in str(c).lower()
                        or "name" in str(c).lower()][0]
            all_vars = [str(v).strip() for v in cb[name_col].dropna()]
            if len(all_vars) > 200:
                for v in all_vars:
                    if v not in df.columns:
                        if v.startswith("Z") and len(v) > 1:
                            df[v] = (RNG.random(n) < 0.05).astype(float)
                        elif v[:1].isalpha() and not any(ch.isdigit() for ch in v):
                            df[v] = np.where(RNG.random(n) < 0.1, -2, 0).astype(float)
                        else:
                            df[v] = np.where(RNG.random(n) < 0.15, -2,
                                             RNG.uniform(0, 5, n)).round(0)
                df = df[[v for v in all_vars if v in df.columns] +
                        [c for c in df.columns if c not in all_vars]]
                print(f"  [codebook] structure aligned: {len(all_vars)} variables")
        except Exception as e:
            print(f"  [codebook] skipped ({e})")
    return df


# ===========================================================================
# TMY3
# ===========================================================================
def make_tmy3_meta(n_stations: int = 1020) -> pd.DataFrame:
    rows = []
    for i in range(n_stations):
        st = STATE_DF.iloc[i % len(STATE_DF)]
        rows.append({
            "station_number": 690000 + i * 137,
            "station_name": f"STATION {st['postal']} {i:04d}",
            "State": st["postal"],
            "Latitude": round(27 + (hash(st["postal"]) % 180) / 10.0 + RNG.normal(0, 1.2), 3),
            "Longitude": round(-125 + (hash(st["postal"][::-1]) % 550) / 10.0, 3),
            "Elevation": int(abs(RNG.normal(400, 500))),
            "Class": RNG.choice(["I", "II", "III"], p=[0.5, 0.3, 0.2]),
        })
    return pd.DataFrame(rows)


def make_tmy3_hourly(meta: pd.DataFrame, n_stations: int = 12) -> pd.DataFrame:
    chosen = meta.iloc[:: max(1, len(meta) // n_stations)].iloc[:n_stations]
    frames = []
    hours = np.arange(8760)
    doy = hours // 24 + 1
    hod = hours % 24
    date = pd.to_datetime("2020-01-01") + pd.to_timedelta(hours, unit="h")
    for _, stn in chosen.iterrows():
        lat = stn["Latitude"]
        st_row = STATE_DF[STATE_DF["postal"] == stn["State"]].iloc[0]
        tmean = 18 - 0.30 * (st_row["hdd"] - 4500) / 1000 * 2 + 0.002 * st_row["cdd"]
        seasonal = -12 * np.cos(2 * np.pi * (doy - 15) / 365) * np.clip((lat - 20) / 25, 0.3, 1.2)
        diurnal = 4.5 * np.sin(2 * np.pi * (hod - 8) / 24)
        tdb = tmean + seasonal + diurnal + RNG.normal(0, 3, 8760)
        ghi = np.clip(650 * np.sin(np.pi * np.clip(hod - 6, 0, 12) / 12) *
                      (0.55 + 0.45 * np.sin(2 * np.pi * (doy - 80) / 365)) *
                      _ln(1, .3, 8760), 0, None)
        dew = np.clip(tdb - RNG.uniform(4, 14, 8760), -30, None)
        rh = np.clip(100 * np.exp((17.27 * dew) / (237.3 + dew) - (17.27 * tdb) / (237.3 + tdb)), 1, 100)
        wspd = np.clip(RNG.gamma(2.2, 1.6, 8760), 0, 40)
        df = pd.DataFrame({
            "Station number": stn["station_number"],
            "Date (MM/DD/YYYY)": date.strftime("%m/%d/%Y"),
            "Time (HH:MM)": [f"{h:02d}:00" for h in hod],
            "GHI (W/m^2)": ghi.round(0), "Dry-bulb (C)": tdb.round(1),
            "Dew-point (C)": dew.round(1), "RHum (%)": rh.round(0),
            "Wspd (m/s)": wspd.round(1),
        })
        for c in TMY3_COLUMNS:
            if c not in df.columns:
                if "source" in c.lower():
                    df[c] = RNG.choice([1, 3, 5, 9], 8760)
                elif "uncert" in c.lower():
                    df[c] = RNG.uniform(0, 5, 8760).round(1)
                elif "Date" in c or "Time" in c or "METAR" in c:
                    df[c] = ""
                else:
                    df[c] = RNG.uniform(0, 100, 8760).round(1)
        frames.append(df[TMY3_COLUMNS])
    return pd.concat(frames, ignore_index=True)


# ===========================================================================
# ResStock 2025.1  (shared building stock -> meaningful upgrade deltas)
# ===========================================================================
UPGRADE_DELTA = {0: 0.0, 3: 0.25, 4: 0.27, 10: 0.06, 11: 0.08, 15: 0.05}
_RS_STOCK_CACHE: dict = {}

RS_BA = ["Hot-Humid", "Hot-Dry", "Marine", "Mixed-Humid", "Mixed-Dry", "Cold", "Very-Cold"]
RS_TYPEHUQ = ["Single-Family Detached", "Single-Family Attached", "Mobile Home",
              "Multi-Family with 2 - 4 Units", "Multi-Family with 5+ Units"]
RS_VINTAGE = ["<1940", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s",
              "2000s", "2010s"]
RS_FUEL = ["Electricity", "Natural Gas", "Propane", "Fuel Oil", "Other Fuel", "Wood"]


def _make_resstock_stock(n_rows: int) -> pd.DataFrame:
    """The SHARED building stock (generated once for the largest request)."""
    if "stock" in _RS_STOCK_CACHE and len(_RS_STOCK_CACHE["stock"]) >= n_rows:
        return _RS_STOCK_CACHE["stock"]
    n = n_rows
    ba = RNG.choice(RS_BA, n, p=[0.28, 0.08, 0.10, 0.24, 0.07, 0.18, 0.05])
    th = RNG.choice(RS_TYPEHUQ, n, p=[0.63, 0.07, 0.06, 0.10, 0.14])
    sqft = np.clip(_ln(1.0, 0.35, n) * np.where(th == "Single-Family Detached", 2300, 1400),
                   300, 6000)
    vintage = RNG.choice(RS_VINTAGE, n)
    fuel = RNG.choice(RS_FUEL, n, p=[0.38, 0.42, 0.06, 0.06, 0.04, 0.04])
    hdd = np.array([{"Hot-Humid": 1600, "Hot-Dry": 1800, "Marine": 4200,
                     "Mixed-Humid": 4300, "Mixed-Dry": 4500, "Cold": 6500,
                     "Very-Cold": 9000}[b] for b in ba])
    cdd = np.array([{"Hot-Humid": 3200, "Hot-Dry": 3000, "Marine": 450,
                     "Mixed-Humid": 1500, "Mixed-Dry": 1200, "Cold": 700,
                     "Very-Cold": 350}[b] for b in ba])
    ua = sqft * RNG.uniform(0.25, 0.55, n)
    heat = ua * hdd * 24 / 3412 * 0.28 * RNG.uniform(0.8, 1.3, n)
    cool = ua * cdd * 24 / 3412 * 0.28 * RNG.uniform(0.7, 1.2, n) * 0.30
    base_other = (8 + sqft / 400) * 365 * RNG.uniform(0.8, 1.3, n) / 1000 * 2.2
    stock = pd.DataFrame({"ba": ba, "th": th, "sqft": sqft, "vintage": vintage,
                          "fuel": fuel, "hdd": hdd, "cdd": cdd, "ua": ua,
                          "heat": heat, "cool": cool, "base_other": base_other})
    _RS_STOCK_CACHE["stock"] = stock
    return stock


def make_resstock_upgrade(upgrade_id: int, n_rows: int) -> pd.DataFrame:
    """All upgrade files share the SAME leading buildings (like real ResStock);
    only the out.* energy results change with the measure."""
    stock = _make_resstock_stock(n_rows).iloc[:n_rows]
    n = len(stock)
    sqft = stock["sqft"].values
    fuel = stock["fuel"].values.copy()
    heat = stock["heat"].values.copy()
    cool = stock["cool"].values.copy()
    base_other = stock["base_other"].values.copy()

    delta = UPGRADE_DELTA.get(upgrade_id, 0.0)
    if upgrade_id in (3, 4):
        heat = heat * (1 - delta) * RNG.uniform(0.9, 1.1, n)
        cool = cool * 0.98
        fuel = np.where(RNG.random(n) < 0.9, "Electricity", fuel)
    elif upgrade_id == 10:
        heat = heat * (1 - 0.06 * RNG.uniform(0.6, 1.4, n))
        cool = cool * (1 - 0.04 * RNG.uniform(0.6, 1.4, n))
    elif upgrade_id == 11:
        heat = heat * (1 - 0.08 * RNG.uniform(0.6, 1.4, n))
        cool = cool * (1 - 0.05 * RNG.uniform(0.6, 1.4, n))
    elif upgrade_id == 15:
        heat = heat * (1 - 0.05 * RNG.uniform(0.6, 1.4, n))
        cool = cool * (1 - 0.07 * RNG.uniform(0.6, 1.4, n))

    total_kwh = np.clip(heat + cool + base_other, 500, 45000)
    elec_share = np.where(fuel == "Electricity", 0.95, RNG.uniform(0.35, 0.6, n))
    elec_kwh = total_kwh * elec_share
    gas_kwh = total_kwh - elec_kwh
    th = stock["th"].values
    ba = stock["ba"].values

    # Make the intervention visible in the in.* attributes (real ResStock
    # upgrade files carry modified building characteristics — without this the
    # upgrade teachers see identical inputs and cannot learn the effect).
    infiltration = RNG.choice(["15 ACH50", "10 ACH50", "7 ACH50"], n)
    insul_roof = RNG.choice(["R-30", "R-38", "R-49"], n)
    insul_ceiling = RNG.choice(["R-19", "R-30", "R-49"], n)
    windows = RNG.choice(["Single, Clear", "Double, Clear", "Double, Low-E"], n)
    if upgrade_id == 10:      # air sealing
        infiltration = np.where(RNG.random(n) < 0.9, "7 ACH50", infiltration)
    elif upgrade_id == 11:    # attic insulation
        insul_roof = np.where(RNG.random(n) < 0.9, "R-49", insul_roof)
        insul_ceiling = np.where(RNG.random(n) < 0.9, "R-49", insul_ceiling)
    elif upgrade_id == 15:    # ENERGY STAR windows
        windows = np.where(RNG.random(n) < 0.9, "Double, Low-E", windows)

    df = pd.DataFrame({
        "bldg_id": np.arange(1, n + 1),           # stable id for upgrade matching
        "in.sqft..ft2": sqft.round(0),
        "in.geometry_building_type_recs": th,
        "in.vintage": stock["vintage"].values,
        "in.geometry_stories": RNG.choice(["One", "Two", "Three"], n, p=[0.55, 0.38, 0.07]),
        "in.bedrooms": RNG.choice(["1", "2", "3", "4", "5"], n, p=[0.1, 0.25, 0.4, 0.2, 0.05]),
        "in.occupants": RNG.choice(["1", "2", "3", "4", "5", "6"], n,
                                   p=[0.25, 0.35, 0.18, 0.12, 0.07, 0.03]),
        "in.heating_fuel": fuel,
        "in.hvac_heating_type": np.where(fuel == "Electricity", "Heat Pump", "Central Furnace"),
        "in.hvac_heating_efficiency": np.where(fuel == "Electricity", "9.5 HSPF", "80% AFUE"),
        "in.hvac_cooling_type": RNG.choice(["Central AC", "Room AC", "None"], n,
                                           p=[0.65, 0.2, 0.15]),
        "in.hvac_cooling_efficiency": "13 SEER",
        "in.insulation_wall": RNG.choice(["R-13", "R-19", "R-21"], n),
        "in.insulation_roof": insul_roof,
        "in.insulation_ceiling": insul_ceiling,
        "in.infiltration": infiltration,
        "in.windows": windows,
        "in.building_america_climate_zone": ba,
        "in.ashrae_iecc_climate_zone_2004": [b.split("-")[0] for b in ba],
        "in.census_region": RNG.choice(["South", "West", "Midwest", "Northeast"], n),
        "in.census_division": RNG.choice(["Pacific", "South Atlantic", "West North Central"], n),
        "in.state": RNG.choice(STATE_DF["postal"].tolist(), n),
        "in.county": RNG.choice(["G0100010", "G0600030", "G4802010"], n),
        "in.puma": RNG.choice(["G01000100", "G06000200"], n),
        "in.weather_file_city": RNG.choice(["USA_AZ_Phoenix", "USA_MN_Minneapolis"], n),
        "in.water_heater_fuel": RNG.choice(["Electricity", "Natural Gas"], n),
        "in.water_heater_efficiency": "0.9 EF",
        "in.has_pv": RNG.choice(["No", "Yes"], n, p=[0.92, 0.08]),
        "in.electric_vehicle_ownership": RNG.choice(["No", "Yes"], n, p=[0.85, 0.15]),
        "in.lighting": "LED",
        "in.ceiling_fan": RNG.choice(["No", "Yes"], n),
        "in.mechanical_ventilation": RNG.choice(["No", "Yes"], n, p=[0.7, 0.3]),
        "out.site_energy.total.energy_consumption..kwh": total_kwh.round(1),
        "out.electricity.total.energy_consumption..kwh": elec_kwh.round(1),
        "out.natural_gas.total.energy_consumption..kwh": np.clip(gas_kwh, 0, None).round(1),
        "out.site_energy.total.energy_consumption_intensity..kwh_per_ft2":
            (total_kwh / np.clip(sqft, 1, None)).round(3),
        "out.utility_bills.total_bill..usd": (total_kwh * 0.13).round(0),
        "out.emissions.total.lrmer_mid_case_25..co2e_kg": (total_kwh * 0.42).round(0),
        "upgrade": upgrade_id,
        "in.upgrade_name": f"upgrade_{upgrade_id}",
        "weight": RNG.uniform(200, 300, n).round(1),
    })
    return df


# ===========================================================================
def make_spatial_lookup(n_rows: int = 200) -> pd.DataFrame:
    cols = [f"col_{i}" for i in range(27)]
    df = pd.DataFrame(RNG.uniform(0, 1, (n_rows, 27)), columns=cols)
    df["col_0"] = [f"G{(i % 56) + 1:02d}{(i % 900) + 10:04d}0" for i in range(n_rows)]
    return df


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--recs-rows", type=int, default=4000)
    ap.add_argument("--resstock-rows", type=int, default=8000)
    ap.add_argument("--tmy3-stations", type=int, default=12)
    ap.add_argument("--meta-stations", type=int, default=1020)
    args = ap.parse_args()

    DATA.mkdir(parents=True, exist_ok=True)
    print(f"[1/5] Generating RECS ({args.recs_rows:,} rows)...")
    recs = make_recs(args.recs_rows)
    recs.to_csv(DATA / "recs2020_public_v7.csv", index=False)
    print(f"      -> {DATA / 'recs2020_public_v7.csv'}  shape={recs.shape}")

    print(f"[2/5] Generating TMY3 meta ({args.meta_stations:,} stations)...")
    meta_path = DATA / "TMY3_StationsMeta.csv"
    if meta_path.exists():
        meta = pd.read_csv(meta_path)
        print(f"      -> real meta found, kept as-is ({len(meta):,} stations)")
    else:
        meta = make_tmy3_meta(args.meta_stations)
        meta.to_csv(meta_path, index=False)
        print(f"      -> {meta_path}  shape={meta.shape}")

    print(f"[3/5] Generating hourly TMY3 ({args.tmy3_stations} stations x 8760 h)...")
    tmy3 = make_tmy3_hourly(meta, args.tmy3_stations)
    tmy3.to_csv(DATA / "tmy3.csv", index=False)
    print(f"      -> {DATA / 'tmy3.csv'}  shape={tmy3.shape}")

    print("[4/5] Generating ResStock upgrades (shared building stock)...")
    _make_resstock_stock(max(args.resstock_rows, 8000))
    for u, frac in [(0, 1.0), (3, 1.0), (4, 1.0), (10, 0.56), (11, 0.92), (15, 0.98)]:
        dfu = make_resstock_upgrade(u, int(args.resstock_rows * frac))
        dfu.to_csv(DATA / f"upgrade{u}.csv.gz", index=False, compression="gzip")
        print(f"      -> {DATA / f'upgrade{u}.csv.gz'}  shape={dfu.shape}")

    print("[5/5] Generating spatial tract lookup...")
    sp = make_spatial_lookup()
    sp.to_csv(DATA / "spatial_tract_lookup_table.csv", index=False)
    print(f"      -> {DATA / 'spatial_tract_lookup_table.csv'}  shape={sp.shape}")
    print("DONE. All synthetic test data generated.")


if __name__ == "__main__":
    main()
